In [42]:
import pandas as pd

In [43]:
df = pd.read_csv("C:\\Users\\MadanRajMA\\Documents\\DS\\Dataset_new\\renewal_calls.csv")

C:\Users\MadanRajMA\AppData\Local\Temp\ipykernel_12444\1196611915.py:1: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:\\Users\\MadanRajMA\\Documents\\DS\\Dataset_new\\renewal_calls.csv")

In [44]:
df

,Call_ID,Call_Direction,Co_Ref,Call_Date,Churn_Category,Complaint_Category,Customer_Reaction_Category,Agent_Renewal_Pitch_Category,Customer_Renewal_Response_Category,Agent_Response_Category,...,Customer_Response,Desire_To_Cancel,Discount_Offered,Justification_Category,Reason_For_Renewal_Category,Agent_Response_To_Cancel_Category,Argument_That_Convinced_Customer_to_Stay_Category,Analysed_Call,Call_Number,Call_Year
0,5.950000e+11,Outbound,UB0899,29-01-2025,NaN,NaN,Not Mentioned,Discussion / Introduction / Inquiry,Discount and Offer,Discount and Offer,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,3,2025
1,5.970000e+11,OUT_BOUND,HN5141,26-02-2025,NaN,NaN,NaN,Price and Cost,Agreement,Customer Communication,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,2,2025
2,5.950000e+11,Outbound,BP5009,24-01-2025,NaN,NaN,NaN,Expiration / Due,Agreement,Accreditation and Certification,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1,2025
3,6.520000e+11,OUT_BOUND,XP8119,09-06-2025,NaN,NaN,NaN,Auto / Automatic,Agreement,Accreditation and Certification,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1,2025
4,5.370000e+11,Outbound,ZL7978,20-08-2024,NaN,NaN,NaN,NaN,NaN,NaN,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,28,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186529,5.050000e+11,Outbound,EE2165,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024
186530,5.050000e+11,Outbound,IT3598,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024
186531,5.050000e+11,Outbound,ZD8460,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024
186532,5.050000e+11,Outbound,PX0289,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024
186533,5.050000e+11,Outbound,IL3891,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024

In [ ]:
new_column_name_snake_case = [
    "call_id", "call_direction", "co_ref", "call_date",
    "churn_category", "complaint_category", "customer_reaction_category",
    "agent_renewal_pitch_category", "customer_renewal_response_category",
    "agent_response_category", "membership_renewal_decision",
    "serious_complaint", "other_complaint", "discussion_on_price_increase",
    "renewal_impact_due_to_price_increase", "discount_or_waiver_requested",
    "call_reschedule_request", "agent_flagged_membership_status_alert",
    "agent_renewal_initiation", "explicit_competitor_mention",
    "unnamed_20", "explicit_switching_intent", "mentioned_competitors",
    "price_switching_mentioned", "competitor_value_comparison",
    "competitor_benefits_mentioned", "topic_introduced_by",
    "percentage_price_increase_mentioned", "monetary_price_increase_mentioned",
    "price_range_mentioned", "customer_asked_for_justification",
    "customer_response", "desire_to_cancel", "discount_offered",
    "justification_category", "reason_for_renewal_category",
    "agent_response_to_cancel_category",
    "argument_that_convinced_customer_to_stay_category",
    "analysed_call", "call_number", "call_year"
]
df.columns
df.columns = new_column_name_snake_case

In [ ]:
df.drop(columns=["unnamed_20"], inplace=True)
df.drop(columns=["call_year"], inplace=True)
df.drop(columns=["agent_renewal_pitch_category"], inplace=True)
df.drop(columns=["customer_renewal_response_category"], inplace=True)
df.drop(columns=["agent_response_category"], inplace=True)

In [47]:
df["call_direction"] = df["call_direction"].replace({"OUT_BOUND": "Outbound", "IN_BOUND": "Inbound"})

In [48]:
df

,call_id,call_direction,co_ref,call_date,churn_category,complaint_category,customer_reaction_category,membership_renewal_decision,serious_complaint,other_complaint,...,customer_asked_for_justification,customer_response,desire_to_cancel,discount_offered,justification_category,reason_for_renewal_category,agent_response_to_cancel_category,argument_that_convinced_customer_to_stay_category,analysed_call,call_number
0,5.950000e+11,Outbound,UB0899,29-01-2025,NaN,NaN,Not Mentioned,No,No,No,...,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,3
1,5.970000e+11,Outbound,HN5141,26-02-2025,NaN,NaN,NaN,No,No,No,...,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,2
2,5.950000e+11,Outbound,BP5009,24-01-2025,NaN,NaN,NaN,No,No,No,...,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1
3,6.520000e+11,Outbound,XP8119,09-06-2025,NaN,NaN,NaN,No,No,No,...,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1
4,5.370000e+11,Outbound,ZL7978,20-08-2024,NaN,NaN,NaN,No,No,No,...,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186529,5.050000e+11,Outbound,EE2165,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
186530,5.050000e+11,Outbound,IT3598,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
186531,5.050000e+11,Outbound,ZD8460,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
186532,5.050000e+11,Outbound,PX0289,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
186533,5.050000e+11,Outbound,IL3891,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [49]:
from sklearn.preprocessing import LabelEncoder

def labelencoder(df, column_name):
    le = LabelEncoder()
    df[column_name] = le.fit_transform(df[column_name].astype(str))
    return df

In [ ]:
del new_column_name_snake_case[20]
yes_no_vals=new_column_name_snake_case[10:23]
yes_no_vals.append("percentage_price_increase_mentioned")
yes_no_vals.append("monetary_price_increase_mentioned")
yes_no_vals.append("customer_asked_for_justification")
yes_no_vals.append("customer_response")
yes_no_vals.append("discount_offered")

['membership_renewal_decision',
 'serious_complaint',
 'other_complaint',
 'discussion_on_price_increase',
 'renewal_impact_due_to_price_increase',
 'discount_or_waiver_requested',
 'call_reschedule_request',
 'agent_flagged_membership_status_alert',
 'agent_renewal_initiation',
 'explicit_competitor_mention',
 'explicit_switching_intent',
 'mentioned_competitors',
 'price_switching_mentioned']

In [51]:
df["discount_or_waiver_requested"] = df["discount_or_waiver_requested"].replace({"Yes, the customer mentioned trying to use a discount code for the renewal.": "Yes", "Yes (Customer inquired about reducing the bill and had a previously applied discount re-applied)": "Yes"})

In [41]:

for col in new_column_name_snake_case[10:24]:
    df = labelencoder(df, col)

df.head()

,call_id,call_direction,co_ref,call_date,churn_category,complaint_category,customer_reaction_category,membership_renewal_decision,serious_complaint,other_complaint,...,customer_asked_for_justification,customer_response,desire_to_cancel,discount_offered,justification_category,reason_for_renewal_category,agent_response_to_cancel_category,argument_that_convinced_customer_to_stay_category,analysed_call,call_number
0,5.950000e+11,Outbound,UB0899,29-01-2025,NaN,NaN,Not Mentioned,0,0,0,...,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,3
1,5.970000e+11,Outbound,HN5141,26-02-2025,NaN,NaN,NaN,0,0,0,...,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,2
2,5.950000e+11,Outbound,BP5009,24-01-2025,NaN,NaN,NaN,0,0,0,...,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1
3,6.520000e+11,Outbound,XP8119,09-06-2025,NaN,NaN,NaN,0,0,0,...,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1
4,5.370000e+11,Outbound,ZL7978,20-08-2024,NaN,NaN,NaN,0,0,0,...,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,28

In [56]:
import pandas as pd

billings_df = pd.read_csv("C:\\Users\\MadanRajMA\\Documents\\DS\\Dataset_new\\billings.csv")
calls_df = pd.read_csv("C:\\Users\\MadanRajMA\\Documents\\DS\\Dataset_new\\cc_calls.csv")
emails_df = pd.read_csv("C:\\Users\\MadanRajMA\\Documents\\DS\\Dataset_new\\emails.csv")
renewal_calls_df = pd.read_csv("C:\\Users\\MadanRajMA\\Documents\\DS\\Dataset_new\\renewal_calls.csv")

C:\Users\MadanRajMA\AppData\Local\Temp\ipykernel_12444\3481780165.py:3: DtypeWarning: Columns (15,16,19,52,53) have mixed types. Specify dtype option on import or set low_memory=False.
  billings_df = pd.read_csv("C:\\Users\\MadanRajMA\\Documents\\DS\\Dataset_new\\billings.csv")
C:\Users\MadanRajMA\AppData\Local\Temp\ipykernel_12444\3481780165.py:5: DtypeWarning: Columns (16,19) have mixed types. Specify dtype option on import or set low_memory=False.
  emails_df = pd.read_csv("C:\\Users\\MadanRajMA\\Documents\\DS\\Dataset_new\\emails.csv")
C:\Users\MadanRajMA\AppData\Local\Temp\ipykernel_12444\3481780165.py:6: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37) have mixed types. Specify dtype option on import or set low_memory=False.
  renewal_calls_df = pd.read_csv("C:\\Users\\MadanRajMA\\Documents\\DS\\Dataset_new\\renewal_calls.csv")

In [62]:
import pandas as pd

# ✅ Optional: Clean column names
for df in [billings_df, calls_df, emails_df, renewal_calls_df]:
    df.columns = df.columns.str.strip()

# ✅ Step 1: Filter emails for Time_to_Renewal = "14_out"
emails_14_out_df = emails_df[emails_df["Time_to_Renewal"] == "14_out"]

# ✅ Step 2: Extract Co_Ref list
co_ref_14_out = emails_14_out_df["Co_Ref"].unique()

# ✅ Step 3: Filter other datasets using Co_Ref
billings_filtered_df = billings_df[billings_df["Co_Ref"].isin(co_ref_14_out)]
calls_filtered_df = calls_df[calls_df["Co_Ref"].isin(co_ref_14_out)]
renewal_calls_filtered_df = renewal_calls_df[renewal_calls_df["Co_Ref"].isin(co_ref_14_out)]

# ✅ Step 4: Save each filtered dataframe to CSV
emails_14_out_df.to_csv(
    "C:\\Users\\MadanRajMA\\Documents\\DS\\Dataset_new\\emails_14_out.csv",
    index=False
)

billings_filtered_df.to_csv(
    "C:\\Users\\MadanRajMA\\Documents\\DS\\Dataset_new\\billings_14_out.csv",
    index=False
)

calls_filtered_df.to_csv(
    "C:\\Users\\MadanRajMA\\Documents\\DS\\Dataset_new\\calls_14_out.csv",
    index=False
)

renewal_calls_filtered_df.to_csv(
    "C:\\Users\\MadanRajMA\\Documents\\DS\\Dataset_new\\renewal_calls_14_out.csv",
    index=False
)